// <auto-generated />
using System;
using LogsManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogsManagement.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(LogsManagementDbContext))]
    [Migration("20250821124622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logs")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CalculationId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DriverFullName")
                        .HasColumnType("text")
                        .HasColumnName("driver_full_name");

                    b.Property<string>("Forestry")
                        .HasColumnType("text")
                        .HasColumnName("forestry");

                    b.Property<decimal>("LogLengthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("log_length_meters");

                    b.Property<string>("OperatorFullName")
                        .HasColumnType("text")
                        .HasColumnName("operator_full_name");

                    b.Property<string>("Quarter")
                        .HasColumnType("text")
                        .HasColumnName("quarter");

                    b.Property<string>("TransportNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_number");

                    b.Property<int>("TransportType")
                        .HasColumnType("integer")
                        .HasColumnName("transport_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_batches");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_batches_calculation_id");

                    b.ToTable("batches", "logs");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.Calculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Gost")
                        .HasColumnType("integer")
                        .HasColumnName("gost");

                    b.Property<int>("LogType")
                        .HasColumnType("integer")
                        .HasColumnName("log_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_calculations");

                    b.ToTable("Calculations", "logs");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Diameter")
                        .HasColumnType("numeric")
                        .HasColumnName("diameter");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_log_entries_batch_id");

                    b.ToTable("log_entries", "logs");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "logs");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.Batch", b =>
                {
                    b.HasOne("LogsManagement.Domain.Entities.Calculation.Calculation", null)
                        .WithMany("Batches")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_batches_calculations_calculation_id");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.LogEntry", b =>
                {
                    b.HasOne("LogsManagement.Domain.Entities.Calculation.Batch", null)
                        .WithMany("LogEntries")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_log_entries_batches_batch_id");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.Batch", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("LogsManagement.Domain.Entities.Calculation.Calculation", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
