<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogsManagement.Common.Domain\LogsManagement.Common.Domain.csproj" />
    <ProjectReference Include="..\LogsManagement.Common\LogsManagement.Common.csproj" />
    <ProjectReference Include="..\LogsManagement.Domain\LogsManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
