# Cursor Automation Workflow Configurations
# Override default settings for different workflow types

# Default settings (applied to all workflows)
defaults:
  workspace: "/home/alex/projects/fin-model"
  timeout: 600                    # 10 minutes
  max_iterations: 50
  loop_threshold: 3
  gui_automation: true
  log_level: "INFO"

# Workflow-specific overrides
workflows:
  2-agent:
    description: "Basic architect + executor workflow"
    timeout: 300                  # 5 minutes for simple tasks
    max_iterations: 30
    
  3-agent:
    description: "Add code review and quality assurance"
    timeout: 900                  # 15 minutes for thorough review
    max_iterations: 75
    
  4-agent:
    description: "Full development lifecycle with GitHub"
    timeout: 1800                 # 30 minutes for complete workflow
    max_iterations: 100
    github_integration: true
    require_tests: true

# Custom agent configurations
custom_agents:
  security_reviewer:
    role: "security"
    channels: ["e2s", "s2a", "status"]
    prompt: |
      ROLE: Security Reviewer - Identify and fix security vulnerabilities
      
      FOCUS AREAS:
      - Input validation and sanitization
      - Authentication and authorization
      - SQL injection prevention
      - XSS protection
      - Secrets management
      - OWASP Top 10 compliance
      
      End messages with [[END-OF-TURN]]

  performance_optimizer:
    role: "performance" 
    channels: ["r2p", "p2a", "status"]
    prompt: |
      ROLE: Performance Optimizer - Identify and fix performance bottlenecks
      
      FOCUS AREAS:
      - Database query optimization
      - Caching strategies
      - Memory usage analysis
      - Load testing results
      - Scalability improvements
      
      End messages with [[END-OF-TURN]]

# Environment-specific settings
environments:
  development:
    log_level: "DEBUG"
    gui_automation: true
    timeout: 300
    
  staging: 
    log_level: "INFO"
    gui_automation: false      # Headless CI/CD
    timeout: 600
    
  production:
    log_level: "WARNING"
    gui_automation: false
    timeout: 1800
    require_approval: true

# Integration settings
integrations:
  github:
    enabled: false
    default_branch: "main"
    pr_template: |
      ## Summary
      Brief description of changes
      
      ## Testing
      - [ ] Unit tests pass
      - [ ] Integration tests pass
      - [ ] Manual testing completed
      
      ## Checklist
      - [ ] Code reviewed
      - [ ] Documentation updated
      - [ ] No secrets committed
    
  slack:
    enabled: false
    webhook_url: ""
    notify_on: ["completion", "errors", "loops"]
    
  jira:
    enabled: false
    server_url: ""
    project_key: ""